### 1.Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [1]:
import numpy as np

In [17]:
x=np.array([3,4,5,6,7])
x


array([3, 4, 5, 6, 7])

In [18]:
np.vander(x) #when N is not determined will return a squared matrix

array([[  81,   27,    9,    3,    1],
       [ 256,   64,   16,    4,    1],
       [ 625,  125,   25,    5,    1],
       [1296,  216,   36,    6,    1],
       [2401,  343,   49,    7,    1]])

In [19]:
np.vander(x,N=3)

array([[ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1],
       [36,  6,  1],
       [49,  7,  1]])

In [20]:
#user defined function

def gen_vander_matrix(ipvector, n, increasing=False):
    a=np.array(ipvector)
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in a for i in range(n)]).reshape(a.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in a for i in range(n)]).reshape(a.size,n)
    
    return op_matx

In [21]:
gen_vander_matrix([1,2,3,4,5],6)

array([[   1,    1,    1,    1,    1,    1],
       [  32,   16,    8,    4,    2,    1],
       [ 243,   81,   27,    9,    3,    1],
       [1024,  256,   64,   16,    4,    1],
       [3125,  625,  125,   25,    5,    1]])

### 2. Write a function to find moving average in an array over a window:Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [22]:
def moving_avg():
    x=int(input("enter the number of elements:"))
    ip=[]
    op=[]
    for i in range(x):
        a=int(input("enter a number"))
        ip.append(a)
    k=int(input("enter window size:"))
    b=x-k+1
    while b>0:
        for i,values in enumerate(ip):
            y=sum(ip[i:i+k])/k
            op.append(y)
            b-=1
    return op
        

In [23]:
moving_avg()

enter the number of elements:13
enter a number3
enter a number5
enter a number7
enter a number2
enter a number8
enter a number10
enter a number11
enter a number65
enter a number72
enter a number81
enter a number99
enter a number100
enter a number150
enter window size:3


[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333,
 83.33333333333333,
 50.0]